title: "CalcConnect"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

url: "https://ay2526s1-cs2103t-f08b-4.github.io"
repository: "AY2526S1-CS2103T-F08B-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
